# Generated by Django 3.2.7 on 2021-10-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=10, verbose_name='Licence plate')),
                ('owner', models.CharField(max_length=200, null=True, verbose_name='Owner')),
                ('vin_code', models.CharField(max_length=13, verbose_name='VIN code')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='Enter Car manufacturer', max_length=200, verbose_name='Manufacturer')),
                ('model', models.CharField(help_text='Enter model name', max_length=200, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_data', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='autoservisas.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='automobilis',
        ),
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis',
        ),
        migrations.RemoveField(
            model_name='uzsakymo_eilute',
            name='paslauga',
        ),
        migrations.RemoveField(
            model_name='uzsakymo_eilute',
            name='uzsakymas',
        ),
        migrations.DeleteModel(
            name='Automobilio_modelis',
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
        migrations.DeleteModel(
            name='Paslauga',
        ),
        migrations.DeleteModel(
            name='Uzsakymas',
        ),
        migrations.DeleteModel(
            name='Uzsakymo_eilute',
        ),
        migrations.AddField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.carmodel', verbose_name='Model'),
        ),
    ]
