# Generated by Django 3.2.7 on 2021-10-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_auto_20211005_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
