# Generated by Django 3.2.7 on 2021-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_rename_due_data_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Processing'), ('d', 'Done'), ('c', 'Canceled')], default='p', help_text='Status', max_length=1),
        ),
    ]
