# Generated by Django 3.2.7 on 2021-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_orderline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Processing'), ('d', 'Done'), ('c', 'Canceled')], default='p', help_text='Status', max_length=1),
        ),
    ]
